### ISSUE TITLE
Placeholder color under IE/Edge

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/react-dates#71]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 1h
Remaining Estimation | 1h

Placeholder color is different for IE/Edge browsers. In firefox its color is `#aaa`, but in IE it is black. Please, check https://opuscapita.github.io/react-dates//branches/master/index.html?currentComponentName=DateInput under IE/Edge and Firefox/Chrome/etc.

Probably can be fixed by
```css
:-ms-input-placeholder, ::-ms-input-placeholder {
  color: #aaa !important;
}
```

Procurement ticket: https://support.jcatalog.com/browse/PROC-6832
Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/356
